### ISSUE TITLE
Add a section to remove non-free stuff from Software Center

### ISSUE THREAD

**Issue by wolftune** [micahflee/fixubuntu#66]
Although there's not a direct privacy concern, the other problem with Ubuntu / Unity is the presence of ads for non-free stuff in the software center and music apps. Could we at least add _links_ to how to turn those things off? That would make fixubuntu a better full solution and have more long-term relevance too, post-Unity-8

**Comment by kim07** [comment]
:+1:

**Comment by micahflee** [comment]
Sure. I think the issue here is that there a ton of things that could be changed in a default install of Ubuntu to improve it, and many of them end up being ideological or people's personal preferences, and I don't really have a process for picking what should get added to this and what shouldn't.

But I think adding a new section at the bottom called "What's next? Other ways to make Ubuntu better" or something with links to some guides for things like this would be fine. Do you have a good link?

**Comment by wolftune** [comment]
@micahflee basically, I agree that there's a whole ton of "everyone should do this" with everyone having different opinions. I think the *key* criteria for FixUbuntu should be:

Is this updating/improving/adding? Not for FixUbuntu, then. Is this turning *off* something arguably malicious / malware / objectionable / and totally unnecessary thing included by default? Consider it.

So, I think *everyone* should use Redshift, period; I never want to use a computer without it. But it isn't a *fix* of some bullshit Ubuntu did, it's just something they failed to include by default. It doesn't belong in FixUbuntu.

Ads for proprietary software in the Software Center and for proprietary music in the music player? That's some bullshit Ubuntu added in by default. FixUbuntu should provide easy reference to making that go away.

**Comment by micahflee** [comment]
Seems like legit criteria :).
